Fitnasty/config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  root 'home#index'

  post "/send_challenge" => 'challenges#send_challenge'
  get '/challenges/search/:keyword', to: 'challenges#search'
  get '/challenges/recent', to: 'challenges#recent'
  get '/challenges/trending', to: 'challenges#trending'
  get '/users/unfollow/:followee_id', to: 'users#unfollow'
  get '/users/follow/:followee_id', to: 'users#follow'

  get 'challenges/search/:keyword', to: 'challenges#search'
  get 'challenges/recent', to: 'challenges#recent'
  get 'challenges/trending', to: 'challenges#trending'
  get '/users/search/:keyword', to: 'users#search'
  get '/users/show_follow', to: 'users#show_follow'

  get '/user_challenges/:challenge_id', to: 'user_challenges#show'
  get '/trends' => "tags#trends", as: :trends

  post '/challenges' => "challenges#create"
  # resources :challenges
  get '/users/current' => "users#current", as: :current
  get '/users/single_user/:id' => "users#single_user", as: :single_user

  get "/home" => "home#index", as: :home
  get "/log_in" => "sessions#new"
  post "/log_in" => "sessions#create"
  get "/log_out" => "sessions#destroy", as: :log_out
  get '/profile' => "static#index", as: :profile
  get "/tabs" => "home#tabs"
  post "/accept_challenge" => "challenges#accept_challenge", as: :accept_challenge

  get '/map' => "home#map"

  resources :users

  get '/users/:user_id/created' => 'challenges#created', as: :created
  get '/users/:user_id/accepted' => 'challenges#accepted', as: :accepted
  get '/users/:user_id/pending' => 'challenges#pending', as: :pending
  get '/users/:user_id/completed' => 'challenges#completed', as: :completed
  get '/users/:user_id/submitted' => 'challenges#submitted', as: :submitted
  get '/users/:user_id/friend_activity' => 'users#friend_activity', as: :friend_activity
  get '/all_challenges' => 'challenges#all'
  get '/challenges/:challenge_id' => 'challenges#show', as: :show
end

Fitnasty/app/models/challenge.rb
class Challenge < ActiveRecord::Base
  has_many :user_challenges
  has_many :users, through: :user_challenges
  has_many :challenge_tags
  has_many :tags, through: :challenge_tags
  belongs_to :user
  validates :title, :description, :location, :latitude, :longitude, presence: true
  before_save :set_default_image_url

  def set_default_image_url
    if self.image_url == "" then self.image_url = "http://www.ipr365.com/wp-content/uploads/2014/03/weightLiftingIcon.png"; end
  end

  def self.accepted_challenges_for_user(user)
  	accepted_user_challenges = UserChallenge.where(accepted?: true, completed?: false, user_id: user).order(updated_at: :desc).to_a
  	accepted_user_challenges.map! do |user_challenge|
  	 self.find(user_challenge.challenge_id)
  	end
  	return accepted_user_challenges.flatten
  end

  def self.top_ten_challenges
    challenges = UserChallenge.select('challenge_id, count(id) as "count"').group("challenge_id").order('count desc').limit(10)
    trending_challenges = []
    challenges.each { |challenge| trending_challenges << Challenge.find(challenge.challenge_id) }
    return trending_challenges
  end

  def self.pending_challenges_for_user(user)
    pending_user_challenges = UserChallenge.where(accepted?: false, completed?: false, user_id: user).to_a
    pending_user_challenges.map! do |user_challenge|
      self.find(user_challenge.challenge_id)
    end
    return pending_user_challenges.flatten
  end

  def self.completed_challenges_for_user(user)
    completed_user_challenges = UserChallenge.where(accepted?: true, completed?: true, user_id: user).order(updated_at: :desc).to_a
    completed_user_challenges.map! do |user_challenge|
      self.find(user_challenge.challenge_id)
    end
    return completed_user_challenges.flatten
  end

  def self.submitted_challenges_for_user(user)
    submitted_user_challenges = Challenge.where(user_id: user).order(updated_at: :desc).to_a
    return submitted_user_challenges.flatten
  end
end

Fitnasty/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :user_challenges
  has_many :challenges, through: :user_challenges
  has_many :challenges


  has_many :followers, through: :follower_follows, source: :follower
  has_many :follower_follows, foreign_key: :followee_id, class_name: "Follow"

  has_many :followees, through: :followee_follows, source: :followee
  has_many :followee_follows, foreign_key: :follower_id, class_name: "Follow"

  validates :first_name, :last_name, :email, :password, presence: true
  validates :email, uniqueness: true
end

Fitnasty/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		render json: User.all
	end

	def current
		render json: current_user
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to user
		else
			redirect_to root_path
		end
	end

	def show
		@user = User.find(params[:id])
		@signed_in_user = User.find(session[:user_id])
		@recent_challenges = Challenge.order('created_at DESC').limit(10)
    @first_recent = @recent_challenges[0]
	end

	def single_user
		render json: User.find(params[:id])
	end

	def search
		matched_users = match_users(params[:keyword])
		render :partial => 'user_results', locals: {users: matched_users}
	end

	def show_follow
		user = User.find(params[:user_id])
		render :partial => 'follow', locals: {user: user}
	end

	def unfollow
		user = User.find(session[:user_id])
		followee = User.find(params[:followee_id])
		Follow.find_by(follower_id: user.id, followee_id: followee.id).delete
		redirect_to user
	end

	def follow
		user = User.find(session[:user_id])
		followee = User.find(params[:followee_id])
		user.followees << followee
		redirect_to user
	end

	def friend_activity
		@user = User.find(params[:user_id])
		@accepted_followee_challenges = UserChallenge.accepted.where(user_id: @user.followees.to_a.map! do |followee| followee.id end).order(updated_at: :desc).flatten
		render :partial => 'friend_activity', locals: {user: @user, accepted: @accepted_followee_challenges, completed: @completed_folowee_challenges}
	end

	private
	def user_params
	  params.require(:user).permit(:first_name, :last_name, :email, :password)
	end

	def match_users(keyword)
		users = []
		users << User.where('first_name LIKE ?', "%#{keyword}%")
		users << User.where('last_name LIKE ?', "%#{keyword}%")
		users << User.where('email LIKE ?', "%#{keyword}%")
		users.flatten.uniq
	end
end

Fitnasty/app/views/users/_challenge_example.html.erb
<div class="item">
  <img src=<%="#{challenge.image_url}"%> class="challenge_image">
  <h1><%= challenge.title %></h1>
  <h3>By <%= challenge.user.first_name %></h3>
  <p><%= challenge.location %></p>
  <p><%= challenge.description %></p>
</div>

Fitnasty/app/views/users/_follow.erb
<%= render :partial => 'vertical_carousel', locals: {user: user} %>

<div id="user_main">
  <form id="user_search">
    <input type="search" id="user_search_input", placeholder="search for users">
  </form>

  <div class="followers">
    <h3 class="follow_title">People following
      <% if current_user.id == user.id %>
        <%= "you" %>
      <% else %>
        <%= user.first_name %>
      <% end %>
    </h3>
    <% user.followers.each do |follower| %>
      <%= render partial: 'user', locals: {user: follower} %>
    <% end %>
  </div>

  <div class="followees">
    <h3 class="follow_title">People
      <% if current_user.id == user.id %>
        <%= "you're following" %>
      <% else %>
        <%= "#{user.first_name}  is following" %>
      <% end %>
    </h3>
    <% user.followees.each do |followee| %>
      <%= render partial: 'user', locals: {user: followee} %>
    <% end %>
  </div>
</div>

Fitnasty/app/views/users/_friend_activity.erb
<div id="followees_accepted_challenges">
	<% if user == current_user %>
  <h3>Get inspired by your friends!</h3>
  <% else %>
  <h3>Get inspired by <%=user.first_name%>'s friends!</h3>
  <% end %>




  <div id="carousel-example-generic" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>


    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% if accepted != [] %>
        <% accepted[1..-1].each_with_index do |user_challenge, index| %>
          <%= render :partial => 'friend_activity_challenge', locals: {user_challenge: user_challenge, user: user_challenge.user, challenge: user_challenge.challenge, index: index} %>
        <% end %>
      <% else %>
        <h3>You have no friends.</h3>
      <% end %>



    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="icon-next"></span>
    </a>
  </div>

</div>

Fitnasty/app/views/users/_friend_activity_challenge.erb
<div class="item <%= "active" if index == 0 %> ">
	<% if user_challenge.completed? %>
			<div class="friend_activity">
				<div id="float-right">
					<img class="activity_challenge_image" src="<%=challenge.image_url%>" width="20%">
				</div>
				<div class="float-left">
					<h3><%= link_to "#{user.first_name} #{user.last_name}", user %></a>
				completed: </h3>
					<h1><%=challenge.title%></h1>
				</div>
			</div>
	<% elsif user_challenge.completed? == false%>
		<div class="friend_activity">
			<div id="float-right">
				<img class="activity_challenge_image" src="<%=challenge.image_url%>" width="20%">
			</div>
			<div>
				<h3><%= link_to "#{user.first_name} #{user.last_name}", user %></a>
			accepted: </h3>
				<h1><%=challenge.title%></h1>
			</div>
		</div>
	<% end %>
</div>

Fitnasty/app/views/users/_friend_selector.html.erb
<section class="friend_selector_lightbox">
  <h2 class="form_header">Choose Friends</h2>
  <form action="/send_challenge" method="post">
		<% User.all.each do |user| %>
		    <li>
		      <%= check_box_tag 'user_ids[]', user.id -%>
		      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
		      <input class="lightbox_challenge_id" name="challenge_id" type="hidden" value="" />
		      <%= h user.first_name -%>
		    </li>
		<% end %>
		<input id="send_challenge_submit" type="submit" value="Send Challenge!">
	</form>
</section>

Fitnasty/app/views/users/_map.html.erb
<section class="map_lightbox">
  <div id="map-canvas">
  </div>
</section>

Fitnasty/app/views/users/_user.html.erb
<div class="user">
  <div class="profile_pic_thumbnail_container">
    <img class="profile_pic_thumbnail" id="<%=user.email%>"src="http://simpleicon.com/wp-content/uploads/user1.png">
  </div>

  <div class="user_info">
      <%= link_to "#{user.first_name} #{user.last_name}", user %></a><br>
      <span>Challenges completed: <%= user.user_challenges.where(completed?: true).count %></span><br>
      <span>Accepted challenges: <%= user.user_challenges.where(accepted?: true, completed?: false).count %>
      </span>
      <br>

      <% @follower_ids = user.followers.select(:id).map(&:id) %>
      <% if @follower_ids.include?(current_user.id) %>
        <div class='unfollow'>
          <%= link_to 'unfollow', "/users/unfollow/#{user.id}", class: "unfollow_link" %>
        </div>
        <% else %>
        <div class='follow'>
          <%= link_to 'follow', "/users/follow/#{user.id}", class: "follow_link"%>
        </div>
      <% end %>
  </div>

</div>

Fitnasty/app/views/users/_user_results.erb
<% users.each do |user| %>
  <%= render :partial => 'user', locals: {user: user} %>
<% end %>

Fitnasty/app/views/users/_vert_bar_user_info.html.erb
<div class="vbar-user">
  <div class="vbar-pic">
    <img class="profile_pic_thumbnail" id="<%=user.email%>"src="http://simpleicon.com/wp-content/uploads/user1.png">
  </div>

  <div>
      <%= link_to "#{user.first_name} #{user.last_name}", user %></a><br>
      <span>Completed: <%= user.user_challenges.where(completed?: true).count %></span><br>
      <span>Accepted: <%= user.user_challenges.where(accepted?: true, completed?: false).count %>
      </span>
      <br>

      <% @follower_ids = user.followers.select(:id).map(&:id) %>
      <% if @follower_ids.include?(current_user.id) %>
        <div class='unfollow'>
          <%= link_to 'unfollow', "/users/unfollow/#{user.id}", class: "unfollow_link" %>
        </div>
        <% else %>
        <div class='follow'>
          <%= link_to 'follow', "/users/follow/#{user.id}", class: "follow_link"%>
        </div>
      <% end %>
  </div>
</div>

Fitnasty/app/views/users/_vertical_carousel.html.erb
<% @non_friends = User.all.select {|follow| follow.followers.exclude?(current_user)} %>

<div id="vbar-div">
  <div class="row-fluid">
    <div class="span6 offset3">
      <div id="myCarousel" class="carousel slide vertical">
          <!-- Carousel items -->

          <!-- Carousel nav -->
<!--           <a id="vbar-control-left" class="carousel-control left" href="#myCarousel" data-slide="prev">‹</a>
          <a id="vbar-control-right" class="carousel-control right" href="#myCarousel" data-slide="next">›</a> -->

          <div id="checkout_button">
            <p>Checkout some</p>
            <p> more users!</p>
          </div>

          <div class="carousel-inner">
              <div class="active item">
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[0]} if @non_friends[0] %>
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[1]} if @non_friends[1] %>
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[2]} if @non_friends[2] %>
              </div>
              <div class="item">
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[3]} if @non_friends[3] %>
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[4]} if @non_friends[4] %>
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[5]} if @non_friends[5] %>
              </div>
              <div class="item">
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[6]} if @non_friends[6] %>
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[7]} if @non_friends[7] %>
                  <%= render partial: 'vert_bar_user_info', locals: {user: @non_friends[8]} if @non_friends[8] %>
              </div>
          </div>

      </div>
    </div>
  </div>
</div>

Fitnasty/app/views/users/show.html.erb
  <div class="lightbox_background">
  </div>
  <%= render 'friend_selector' %>
<header id="top-nav">
  <form id="search-form">
    <input id="search" type="text" name="query" placeholder="Search for challenges">
  </form>
  <div class="sign_out_div">
    <a href="<%=log_out_path%>" class="signout_button">Sign Out</a>
  </div>
  <div>
    <%= link_to 'FitFriends | ', @signed_in_user, :id => "brand" %>
    <%= link_to "#{@user.first_name} #{@user.last_name}", @signed_in_user, :id => "username" %>
  </div>



</header>

<main class="profile_container">

  <!-- Tabs -->
  <div id="tabs">
    <div class="top_tabs_nav_bar">
      <div class="left-nav">
        <section id="profile-image-container avatar">
          <img class='profile_image' src="http://simpleicon.com/wp-content/uploads/user1.png">
        </section>
        <% if @user != @signed_in_user %>
          <% @follower_ids = @user.followers.select(:id).map(&:id) %>
          <% if @follower_ids.include?(current_user.id) %>
            <div class='unfollow'>
              <%= link_to 'unfollow', "/users/unfollow/#{@user.id}", class: "unfollow_link" %>
            </div>
            <% else %>
            <div class='follow'>
              <%= link_to 'follow', "/users/follow/#{@user.id}", class: "follow_link"%>
            </div>
          <% end %>
        <% end %>
      </div>
      <ul class="tabs_list">
        <li class="tab" id="challenges_tab"><a href="#challenges">Challenges</a></li>
        <li class="tab" id="users_tab"><a id="user_tab" href="#users">Users</a></li>
        <li class="tab" id="friend_activity_tab"><a id="friend_activity_tab" href="#friend_activity">Friend Activity</a></li>
      </ul>
    </div>

    <div class="tab_area" id="challenges">
      <section id="challenges-container">
        <div id="challenge_buttons">
          <button id = "create_challenge" class="test_show challenge_buttons">Create</button>
          <button id = "accepted" class="challenge_buttons">Accepted</button>
          <button id = "most_recent" class="challenge_buttons"> Recent </button>
          <button id = "trending" class="challenge_buttons"> Trending </button>
          <button id = "completed" class="challenge_buttons"> Completed </button>
          <button id = "pending" class="challenge_buttons"> Pending </button>
          <button id = "submitted" class="challenge_buttons"> Submitted </button>
        </div>
        <div class="map_challenge_container">
          <section class="map_container">
            <!-- <div id="panel">
              <input id="address" type="textbox" value="Sydney, NSW">
              <input type="button" value="Geocode" class="map_button">
            </div> -->
            <div id="map-canvas">
            </div>
          </section>
          <div class="challenges_river">
          </div>
        </div>
      </section>
    </div>

    <div class="tab_area" id="users">
      <%= render :partial => 'follow', locals: {user: @user} %>
    </div>

    <div class="tab_area" id="friend_activity">

    </div>
  </div>
</main>